<?php

namespace Database\Seeders;

use App\Models\Bank;
use Illuminate\Database\Seeder;

class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $bank = array(
            array('id' => '1','name' => 'BANK BRI','icon' => '/images/common/bank/bri-5ff7f0ab8fab6.png','code' => '002'),
            array('id' => '2','name' => 'BANK EKSPOR INDONESIA','icon' => '/images/common/bank/logotok-5ff7e1b6df8d2.png','code' => '003'),
            array('id' => '3','name' => 'BANK MANDIRI','icon' => '/images/common/bank/mandiri-5ff7f0b595d8c.png','code' => '008'),
            array('id' => '4','name' => 'BANK BNI','icon' => '/images/common/bank/bni-5ff7e06e8403b.jpeg','code' => '009'),
            array('id' => '5','name' => 'BANK DANAMON','icon' => '/images/common/bank/danamon-5ff7e07a9351c.jpeg','code' => '011'),
            array('id' => '6','name' => 'PERMATA BANK','icon' => NULL,'code' => '013'),
            array('id' => '7','name' => 'BANK BCA','icon' => '/images/common/bank/bca-5ff82791cf85f.png','code' => '014'),
            array('id' => '8','name' => 'BANK BII','icon' => NULL,'code' => '016'),
            array('id' => '9','name' => 'BANK PANIN','icon' => NULL,'code' => '019'),
            array('id' => '10','name' => 'BANK ARTA NIAGA KENCANA','icon' => NULL,'code' => '020'),
            array('id' => '11','name' => 'BANK NIAGA','icon' => NULL,'code' => '022'),
            array('id' => '12','name' => 'BANK BUANA IND','icon' => NULL,'code' => '023'),
            array('id' => '13','name' => 'BANK LIPPO','icon' => NULL,'code' => '026'),
            array('id' => '14','name' => 'BANK NISP','icon' => NULL,'code' => '028'),
            array('id' => '15','name' => 'AMERICAN EXPRESS BANK LTD','icon' => NULL,'code' => '030'),
            array('id' => '16','name' => 'CITIBANK N.A.','icon' => NULL,'code' => '031'),
            array('id' => '17','name' => 'JP. MORGAN CHASE BANK, N.A.','icon' => NULL,'code' => '032'),
            array('id' => '18','name' => 'BANK OF AMERICA, N.A','icon' => NULL,'code' => '033'),
            array('id' => '19','name' => 'ING INDONESIA BANK','icon' => NULL,'code' => '034'),
            array('id' => '20','name' => 'BANK MULTICOR TBK.','icon' => NULL,'code' => '036'),
            array('id' => '21','name' => 'BANK ARTHA GRAHA','icon' => NULL,'code' => '037'),
            array('id' => '22','name' => 'BANK CREDIT AGRICOLE INDOSUEZ','icon' => NULL,'code' => '039'),
            array('id' => '23','name' => 'THE BANGKOK BANK COMP. LTD','icon' => NULL,'code' => '040'),
            array('id' => '24','name' => 'THE HONGKONG & SHANGHAI B.C.','icon' => NULL,'code' => '041'),
            array('id' => '25','name' => 'THE BANK OF TOKYO MITSUBISHI UFJ LTD','icon' => NULL,'code' => '042'),
            array('id' => '26','name' => 'BANK SUMITOMO MITSUI INDONESIA','icon' => NULL,'code' => '045'),
            array('id' => '27','name' => 'BANK DBS INDONESIA','icon' => NULL,'code' => '046'),
            array('id' => '28','name' => 'BANK RESONA PERDANIA','icon' => NULL,'code' => '047'),
            array('id' => '29','name' => 'BANK MIZUHO INDONESIA','icon' => NULL,'code' => '048'),
            array('id' => '30','name' => 'STANDARD CHARTERED BANK','icon' => NULL,'code' => '050'),
            array('id' => '31','name' => 'BANK ABN AMRO','icon' => NULL,'code' => '052'),
            array('id' => '32','name' => 'BANK KEPPEL TATLEE BUANA','icon' => NULL,'code' => '053'),
            array('id' => '33','name' => 'BANK CAPITAL INDONESIA, TBK.','icon' => NULL,'code' => '054'),
            array('id' => '34','name' => 'BANK BNP PARIBAS INDONESIA','icon' => NULL,'code' => '057'),
            array('id' => '35','name' => 'BANK UOB INDONESIA','icon' => NULL,'code' => '058'),
            array('id' => '36','name' => 'KOREA EXCHANGE BANK DANAMON','icon' => NULL,'code' => '059'),
            array('id' => '37','name' => 'RABOBANK INTERNASIONAL INDONESIA','icon' => NULL,'code' => '060'),
            array('id' => '38','name' => 'ANZ PANIN BANK','icon' => NULL,'code' => '061'),
            array('id' => '39','name' => 'DEUTSCHE BANK AG.','icon' => NULL,'code' => '067'),
            array('id' => '40','name' => 'BANK WOORI INDONESIA','icon' => NULL,'code' => '068'),
            array('id' => '41','name' => 'BANK OF CHINA LIMITED','icon' => NULL,'code' => '069'),
            array('id' => '42','name' => 'BANK BUMI ARTA','icon' => NULL,'code' => '076'),
            array('id' => '43','name' => 'BANK EKONOMI','icon' => NULL,'code' => '087'),
            array('id' => '44','name' => 'BANK ANTARDAERAH','icon' => NULL,'code' => '088'),
            array('id' => '45','name' => 'BANK HAGA','icon' => NULL,'code' => '089'),
            array('id' => '46','name' => 'BANK IFI','icon' => NULL,'code' => '093'),
            array('id' => '47','name' => 'BANK CENTURY, TBK.','icon' => NULL,'code' => '095'),
            array('id' => '48','name' => 'BANK MAYAPADA','icon' => NULL,'code' => '097'),
            array('id' => '49','name' => 'BANK JABAR','icon' => NULL,'code' => '110'),
            array('id' => '50','name' => 'BANK DKI','icon' => NULL,'code' => '111'),
            array('id' => '51','name' => 'BPD DIY','icon' => NULL,'code' => '112'),
            array('id' => '52','name' => 'BANK JATENG','icon' => '/images/common/bank/jateng-5ff7e0872c355.jpeg','code' => '113'),
            array('id' => '53','name' => 'BANK JATIM','icon' => NULL,'code' => '114'),
            array('id' => '54','name' => 'BPD JAMBI','icon' => NULL,'code' => '115'),
            array('id' => '55','name' => 'BPD ACEH','icon' => NULL,'code' => '116'),
            array('id' => '56','name' => 'BANK SUMUT','icon' => NULL,'code' => '117'),
            array('id' => '57','name' => 'BANK NAGARI','icon' => NULL,'code' => '118'),
            array('id' => '58','name' => 'BANK RIAU','icon' => NULL,'code' => '119'),
            array('id' => '59','name' => 'BANK SUMSEL','icon' => NULL,'code' => '120'),
            array('id' => '60','name' => 'BANK LAMPUNG','icon' => NULL,'code' => '121'),
            array('id' => '61','name' => 'BPD KALSEL','icon' => NULL,'code' => '122'),
            array('id' => '62','name' => 'BPD KALIMANTAN BARAT','icon' => NULL,'code' => '123'),
            array('id' => '63','name' => 'BPD KALTIM','icon' => NULL,'code' => '124'),
            array('id' => '64','name' => 'BPD KALTENG','icon' => NULL,'code' => '125'),
            array('id' => '65','name' => 'BPD SULSEL','icon' => NULL,'code' => '126'),
            array('id' => '66','name' => 'BANK SULUT','icon' => NULL,'code' => '127'),
            array('id' => '67','name' => 'BPD NTB','icon' => NULL,'code' => '128'),
            array('id' => '68','name' => 'BPD BALI','icon' => NULL,'code' => '129'),
            array('id' => '69','name' => 'BANK NTT','icon' => NULL,'code' => '130'),
            array('id' => '70','name' => 'BANK MALUKU','icon' => NULL,'code' => '131'),
            array('id' => '71','name' => 'BPD PAPUA','icon' => NULL,'code' => '132'),
            array('id' => '72','name' => 'BANK BENGKULU','icon' => NULL,'code' => '133'),
            array('id' => '73','name' => 'BPD SULAWESI TENGAH','icon' => NULL,'code' => '134'),
            array('id' => '74','name' => 'BANK SULTRA','icon' => NULL,'code' => '135'),
            array('id' => '75','name' => 'BANK NUSANTARA PARAHYANGAN','icon' => NULL,'code' => '145'),
            array('id' => '76','name' => 'BANK SWADESI','icon' => NULL,'code' => '146'),
            array('id' => '77','name' => 'BANK MUAMALAT','icon' => NULL,'code' => '147'),
            array('id' => '78','name' => 'BANK MESTIKA','icon' => NULL,'code' => '151'),
            array('id' => '79','name' => 'BANK METRO EXPRESS','icon' => NULL,'code' => '152'),
            array('id' => '80','name' => 'BANK SHINTA INDONESIA','icon' => NULL,'code' => '153'),
            array('id' => '81','name' => 'BANK MASPION','icon' => NULL,'code' => '157'),
            array('id' => '82','name' => 'BANK HAGAKITA','icon' => NULL,'code' => '159'),
            array('id' => '83','name' => 'BANK GANESHA','icon' => NULL,'code' => '161'),
            array('id' => '84','name' => 'BANK WINDU KENTJANA','icon' => NULL,'code' => '162'),
            array('id' => '85','name' => 'HALIM INDONESIA BANK','icon' => NULL,'code' => '164'),
            array('id' => '86','name' => 'BANK HARMONI INTERNATIONAL','icon' => NULL,'code' => '166'),
            array('id' => '87','name' => 'BANK KESAWAN','icon' => NULL,'code' => '167'),
            array('id' => '88','name' => 'BANK TABUNGAN NEGARA (PERSERO)','icon' => NULL,'code' => '200'),
            array('id' => '89','name' => 'BANK HIMPUNAN SAUDARA 1906, TBK .','icon' => NULL,'code' => '212'),
            array('id' => '90','name' => 'BANK TABUNGAN PENSIUNAN NASIONAL','icon' => NULL,'code' => '213'),
            array('id' => '91','name' => 'BANK SWAGUNA','icon' => NULL,'code' => '405'),
            array('id' => '92','name' => 'BANK JASA ARTA','icon' => NULL,'code' => '422'),
            array('id' => '93','name' => 'BANK MEGA','icon' => NULL,'code' => '426'),
            array('id' => '94','name' => 'BANK JASA JAKARTA','icon' => NULL,'code' => '427'),
            array('id' => '95','name' => 'BANK BUKOPIN','icon' => NULL,'code' => '441'),
            array('id' => '96','name' => 'BANK SYARIAH MANDIRI','icon' => NULL,'code' => '451'),
            array('id' => '97','name' => 'BANK BISNIS INTERNASIONAL','icon' => NULL,'code' => '459'),
            array('id' => '98','name' => 'BANK SRI PARTHA','icon' => NULL,'code' => '466'),
            array('id' => '99','name' => 'BANK JASA JAKARTA','icon' => NULL,'code' => '472'),
            array('id' => '100','name' => 'BANK BINTANG MANUNGGAL','icon' => NULL,'code' => '484'),
            array('id' => '101','name' => 'BANK BUMIPUTERA','icon' => NULL,'code' => '485'),
            array('id' => '102','name' => 'BANK YUDHA BHAKTI','icon' => NULL,'code' => '490'),
            array('id' => '103','name' => 'BANK MITRANIAGA','icon' => NULL,'code' => '491'),
            array('id' => '104','name' => 'BANK AGRO NIAGA','icon' => NULL,'code' => '494'),
            array('id' => '105','name' => 'BANK INDOMONEX','icon' => NULL,'code' => '498'),
            array('id' => '106','name' => 'BANK ROYAL INDONESIA','icon' => NULL,'code' => '501'),
            array('id' => '107','name' => 'BANK ALFINDO','icon' => NULL,'code' => '503'),
            array('id' => '108','name' => 'BANK SYARIAH MEGA','icon' => NULL,'code' => '506'),
            array('id' => '109','name' => 'BANK INA PERDANA','icon' => NULL,'code' => '513'),
            array('id' => '110','name' => 'BANK HARFA','icon' => NULL,'code' => '517'),
            array('id' => '111','name' => 'PRIMA MASTER BANK','icon' => NULL,'code' => '520'),
            array('id' => '112','name' => 'BANK PERSYARIKATAN INDONESIA','icon' => NULL,'code' => '521'),
            array('id' => '113','name' => 'BANK AKITA','icon' => NULL,'code' => '525'),
            array('id' => '114','name' => 'LIMAN INTERNATIONAL BANK','icon' => NULL,'code' => '526'),
            array('id' => '115','name' => 'ANGLOMAS INTERNASIONAL BANK','icon' => NULL,'code' => '531'),
            array('id' => '116','name' => 'BANK DIPO INTERNATIONAL','icon' => NULL,'code' => '523'),
            array('id' => '117','name' => 'BANK KESEJAHTERAAN EKONOMI','icon' => NULL,'code' => '535'),
            array('id' => '118','name' => 'BANK UIB','icon' => NULL,'code' => '536'),
            array('id' => '119','name' => 'BANK ARTOS IND','icon' => NULL,'code' => '542'),
            array('id' => '120','name' => 'BANK PURBA DANARTA','icon' => NULL,'code' => '547'),
            array('id' => '121','name' => 'BANK MULTI ARTA SENTOSA','icon' => NULL,'code' => '548'),
            array('id' => '122','name' => 'BANK MAYORA','icon' => NULL,'code' => '553'),
            array('id' => '123','name' => 'BANK INDEX SELINDO','icon' => NULL,'code' => '555'),
            array('id' => '124','name' => 'BANK VICTORIA INTERNATIONAL','icon' => NULL,'code' => '566'),
            array('id' => '125','name' => 'BANK EKSEKUTIF','icon' => NULL,'code' => '558'),
            array('id' => '126','name' => 'CENTRATAMA NASIONAL BANK','icon' => NULL,'code' => '559'),
            array('id' => '127','name' => 'BANK FAMA INTERNASIONAL','icon' => NULL,'code' => '562'),
            array('id' => '128','name' => 'BANK SINAR HARAPAN BALI','icon' => NULL,'code' => '564'),
            array('id' => '129','name' => 'BANK HARDA','icon' => NULL,'code' => '567'),
            array('id' => '130','name' => 'BANK FINCONESIA','icon' => NULL,'code' => '945'),
            array('id' => '131','name' => 'BANK MERINCORP','icon' => NULL,'code' => '946'),
            array('id' => '132','name' => 'BANK MAYBANK INDOCORP','icon' => NULL,'code' => '947'),
            array('id' => '133','name' => 'BANK OCBC – INDONESIA','icon' => NULL,'code' => '948'),
            array('id' => '134','name' => 'BANK CHINA TRUST INDONESIA','icon' => NULL,'code' => '949'),
            array('id' => '135','name' => 'BANK COMMONWEALTH','icon' => NULL,'code' => '950'),
            array('id' => '136','name' => 'Bank BSI','icon' => NULL,'code' => '451')
        );

        foreach ($bank as $v) {
            Bank::Create([
                'id' => $v['id'],
                'name' => $v['name'],
                'icon' => $v['icon'],
                'code' => $v['code'],
            ]);
        }
    }
}
